# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=5)),
            ],
        ),
    ]
